### ISSUE TITLE
undesired action with email sharer: create a new tab

### ISSUE THREAD

**Issue by jimblue** [MaxArt2501/share-this#12]
Hi,

It's not really a bug but really ugly 🤓  !

Because of `target"_blank"` in the `mailto` link a new tab is create in browser on click.

Can you remove this attribute please?
It's not needed for `mailto` link as it will always open the mail client which is a different program.

Thank you 😄

**Comment by MaxArt2501** [comment]
Although I don't consider the sharers a vital part of this package, the request is fair enough. I'll do that for the next release.

And since I have no idea when the next release will be, in the meanwhile you can work around the problem by redefining the `render` method of the email sharer, e.g.:

```javascript
import * as emailSharer from "share-this/dist/sharers/email";

emailSharer.render = function render(text, rawText, refUrl) {
    const url = this.getShareUrl(text, refUrl);

    return `<a href="${url}" rel="noopener nofollow noreferrer">`
        + 'Look ma, no target="_blank"!</a>';
};
```

**Comment by jimblue** [comment]
ok @MaxArt2501 ! of course sooner is better 😆  !

thanks man

**Comment by MaxArt2501** [comment]
Scratch that, I'm on a train, I did it a moment ago 😄 

Happy coding!

**Comment by jimblue** [comment]
Haha nice, thank you man, coding on the rails I know that too 😄 
Have a safe trip!
