### ISSUE TITLE
Popover is not in sync with scrollable/movable content

### ISSUE THREAD

**Issue by bdurrer** [MaxArt2501/share-this#16]
a demo of the problem can be found here: https://jsfiddle.net/0swr3m18/

1. select content in the scrollable div
2. scroll

**actual:** the popup's position is wrong
**expected:** the popup stays with the content

share-this cannot solve the problem itself, since it cannot track all possible ways how content could move.
However, there is currently no way for users of the library to trigger a refresh of the popover.

Request: Expose a redraw/refresh function, as shown in PR #15

**Comment by MaxArt2501** [comment]
Possible enhancement: exposing a `reposition` (or similarly named) method that could be attached to a `scroll` event listener or called for whatever reason.

**Comment by RigaNik** [comment]
@MaxArt2501 when can we expect this to be implemented? Thanks Max

**Comment by MaxArt2501** [comment]
Perhaps during this winter vacation I'll be able to take some time to look into it. Thank you for your patience.

**Comment by MaxArt2501** [comment]
Closed as per 22d37b6.
