### ISSUE TITLE
Feature request: ability to change email icon

### ISSUE THREAD

**Issue by jimblue** [MaxArt2501/share-this#18]
Social icon are pretty much all the same but there is no standard for icon.

Because of that it can break the design and uniformity and it could be nice to be able to change it in the config of each sharers.

By the way I've shared above a mail icon that would probably be a better choice than the actual one.
It is plain like other sharers contrary of the actual mail icon that is outline...

```svg
<svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMinYMin meet" width="32px" height="32px" viewBox="0 0 32 32">
<path d="M4.527 9.819l.983-.983 10.489 8.991 10.489-8.991.983.983-11.473 9.834L4.525 9.819zM3.221 6.26A2.435 2.435 0 0 0 .782 8.688v14.624a2.428 2.428 0 0 0 2.439 2.428H28.78a2.435 2.435 0 0 0 2.439-2.428V8.688A2.428 2.428 0 0 0 28.78 6.26H3.221z"/>
</svg>
```

**Comment by MaxArt2501** [comment]
Just don't use the provided email sharer. Create your own. Or maybe extend the provided on, replacing it `render` method.

The default sharers are *not* a vital part of the library, they're provided as an example. Yours is a nice icon, by the way. Is is free to use?

I'll leave this open as maybe I'll add an `icon` property to each sharer later. It couldn't hurt.

**Comment by jimblue** [comment]
Ok sounds good 😄 

Sorry if it's sound newbie but could you show me how to extend the mail icon by replacing the render method as you said...

Thank you man
