### ISSUE TITLE
Positioning fails if <html> element have a `margin-top`

### ISSUE THREAD

**Issue by ryuran** [MaxArt2501/share-this#21]
Hello,

Yes, I know, a margin on `<html>` element seems awful.
But in my case a advertisement do it, I can’t fix it.

So this function fail to return real position of the root element.
https://github.com/MaxArt2501/share-this/blob/master/src/dom.js#L1-L6

**Comment by MaxArt2501** [comment]
Yes, it does seem awful but it's probably worth considering if it doesn't take much effort.
I have something in mind, I'll look into it.

**Comment by ryuran** [comment]
I realize my solution can’t work if `<html>` has a non-static position

**Comment by ryuran** [comment]
```javascript
export function getOffsetScroll(_window) {
    const body = _window.document.body;
    const html = _window.document.documentElement;
    const ref = (_window.getComputedStyle(body).position !== "static") ? body : html;

    if (_window.getComputedStyle(ref).position !== "static") {
        return ref.getBoundingClientRect();
    }

    const left = window.pageXOffset || ref.scrollLeft;
    const top = window.pageYOffset || ref.scrollTop;

    return {
        left: left * -1,
        top: top * -1
    };
}
```

**Comment by MaxArt2501** [comment]
As I've said on #22, we can't use `pageX`/`YOffset` and similar properties, as they break pinch-to-zoom.

**Comment by ryuran** [comment]
I saw it. I understand 😢 
I can't see other way than get computed margin-top if position is static.

**Comment by MaxArt2501** [comment]
For this limited case, I don't see any reasonable effort to fix this behaviour.

Fortunately, you can easily work around the problem by adding the same top margin to the `.share-this-popover` CSS class:

    .share-this-popover {
        margin-top: 50px; /* or whatever that is... */
    }

**Comment by ryuran** [comment]
😢  this margin on `<html>` is added by an advertissement, not on every page and not if ab are blocked. It is really not easy to know when we have the margin or not. I need to check it when the popover appear.

I will try it.

**Comment by MaxArt2501** [comment]
I honestly wasn't aware that ads were *that* pesky 😕
Fortunately for you, you still have a chance of action setting the `onOpen` handler, which gets called every time the popover is opened, and gives you a reference to the popover's element. Then you can set its top margin at runtime (which is also better, as you can't be sure if that margin is there or not, so you can check right before).
