### ISSUE TITLE
Missing ShareThisViaNotes

### ISSUE THREAD

**Issue by Kosmonaft** [MaxArt2501/share-this#23]
Hello, 

In the demo (https://maxart2501.github.io/share-this/) I can see there is an option to add selection to notes.
As well checking the Resources of the page there is a sharer named: "notes.js" 

Why this sharer is missing from the repository?

**Comment by MaxArt2501** [comment]
Because it's just part of the demo. There are also sharers for Hackernews and... the speakers, through voice synth.

The point is that sharers are *not* part of the package, and they're not included anywhere. The
