### ISSUE TITLE
BUG: share-this display with empty selection

### ISSUE THREAD

**Issue by jimblue** [MaxArt2501/share-this#24]
Hi,

Just want to report a small bug.

If double click on a line-end it can select a space or a line-break.
Because share-this doesn't check the selection length when the previous happen, share-this popup.

You should add  condition check to handle this (for exemple `selection > 1`)

**Here is a screenshot so you can see by yourself the BUG:**
<img width="347" alt="screen shot 2017-12-30 at 11 25 35" src="https://user-images.githubusercontent.com/10623367/34453408-aad521ba-ed54-11e7-9ee7-a0320fa4da20.png">

**Comment by jimblue** [comment]
Maybe a `min length` param could be added?

**An other case where it happen (space between two worlds):**
<img width="359" alt="screen shot 2017-12-30 at 11 32 18" src="https://user-images.githubusercontent.com/10623367/34453421-1cd270ec-ed55-11e7-9a37-f6b43ea31e4f.png">

**Comment by MaxArt2501** [comment]
In the first case, the selection *seems* to be empty, but it actually embraces some white spaces, so it's not "collapsed", using the jargon from [the Selection API](https://developer.mozilla.org/en-US/docs/Web/API/Range/collapsed) and so it has a right to be "shared" (I won't preclude this possibility).

If you don't want the popover to appear when the selection is made of just white spaces, I suggest to add an `active` method to your sharerd that returns `false` when the selection is made of only white spaces. For example:

```javascript
active(text, rawText) {
  return /\S/.test(rawText);
}
// or, if you're using the default transformer:
active(test) {
  return !!text;
}
```

**Comment by jimblue** [comment]
Sorry @MaxArt2501, I don't get how to implement your solution in a custom sharer. (a bit newbie)
Could help a bit more? Thank you so much 😄

**Comment by jimblue** [comment]
Ok just found the solution thank you!!! 😄
