### ISSUE TITLE
z-index

### ISSUE THREAD

**Issue by jimblue** [MaxArt2501/share-this#25]
Hello and happy new year!

I've notice a small improvement because of a bug on my side.

There is no way to modify the z-index.

Could you had a variable so we can adapt it to each case?

Thank you so much

**Comment by MaxArt2501** [comment]
The provided style sheet doesn't even set the `z-index` property anywhere. If you want to do it, you can set it yourself in your own CSS:

```css
.share-this-popover { z-index: 100; }
```

**Comment by jimblue** [comment]
ok
