### ISSUE TITLE
How to change append selector?

### ISSUE THREAD

**Issue by juxteby** [MaxArt2501/share-this#31]
I see that the .share-this-popover is appended at the end of the body tag. Is there a way to change this to append it in another selector? Thanks.

**Comment by MaxArt2501** [comment]
Sorry for the late answer.
Yes, if you define a callback with the `onOpen` setting you can re-attach the popover wherever you want. But you're on your own then.
If you're wondering if you can specify the attach point of the popover when instantiating the service, you can't.  It's been deemed too cumbersome to track scrolling and visibility when the popover isn't on the body.
Closing this for now. If you have other questions, ask away.
