### ISSUE TITLE
LinkedIn not pulling in data

### ISSUE THREAD

**Issue by johncionci** [MaxArt2501/share-this#34]
Im using the default implementation of the script and Facebook and Twitter are pull in dynamic text thats highlighted but LinkedIn opens the sharing window but dosent seem to be pulling in anything.

```
  var twitterSharer = window.ShareThisViaTwitter;
  var facebookSharer = window.ShareThisViaFacebook;
  var linkedinSharer = window.ShareThisViaLinkedIn;
  ShareThis({
    sharers: [ facebookSharer, twitterSharer, linkedinSharer ],
  }).init();
```

**Comment by omegerard** [comment]
Same issue here.

**Comment by MaxArt2501** [comment]
It looks like LinkedIn doesn't support sharing portions of text. The URL for creating sharing posts/messages is now `https://www.linkedin.com/sharing/share-offsite/?url={url}&title={title}` but it doesn't seem to do anything with `title` 🤷‍♂️
Thanks, Microsoft.

As it has lost it purpose, I'm going to pull the sharer from the next release.
