### ISSUE TITLE
Latest release(1.3.0)  is a breaking change.

### ISSUE THREAD

**Issue by shri3k** [MaxArt2501/share-this#37]
I'd consider removal of "linked-in" a breaking change (definitely broke our build). Would it be better to bump the version to `2.0.0` instead?
Thank You.

**Comment by MaxArt2501** [comment]
Man, I regret they putting those sharers inside the library 😩

They weren't meant to be a core part of the library, but rather an example. But I understand your point of view.

I'm planning to remove *all* the sharers in version 2, and move them in their own respective package. Would it be acceptable to restore the LinkedIn sharer (with limited functionality and a console warning) instead for version 1.3.1? This could be done in a short time (later today).

**Comment by shri3k** [comment]
Hey, no worries. Just thought I'd let you know. We got around the problem no problem. :)
