### ISSUE TITLE
cannot change the background color of the popup

### ISSUE THREAD

**Issue by nawras-albaghdadi** [MaxArt2501/share-this#49]

**Comment by MaxArt2501** [comment]
Please add some additional information.

**Comment by nawras-albaghdadi** [comment]
I'm trying to change the `background-color` for the `.share-this-popover` but I could not do that, i changed only the icons using `content: URL(..)` but anything related to the background-color is not working

**Comment by nawras-albaghdadi** [comment]
also,  default CSS from the dis folder was not applied

**Comment by MaxArt2501** [comment]
I was about to say that all you have to do is to redefine the `$share-this-background` SCSS variable (with a `@` for LESS) and recompile the stylesheet. Or even just override the declarations for `.share-this-popover > ul` and so on.

But it looks like you just had some troubles loading the compiled stylesheet. Was that the case?

**Comment by nawras-albaghdadi** [comment]
I think it is something with my dev environment, still checking,
