### ISSUE TITLE
Translate 

### ISSUE THREAD

**Issue by coding1bro** [MaxArt2501/share-this#53]
I have A One Suggestion For You......

● That Add One another option in **Pop-Up Window** that , _**It Will Translate The Word or Sentence In User's Mother Tongue**_
•So that users can easily read and understand the **blogs** and **readable content** .

**Comment by MaxArt2501** [comment]
Hello, what do you mean by that? Are you proposing a new sharer?
Because that would be out of scope of this library.

**Comment by coding1bro** [comment]
> Hello, what do you mean by that? Are you proposing a new sharer?
> Because that would be out of scope of this library.

So Sorry 😔,
I have a less knowledge about it....
I just asked about it,I am new/beginner of javascript and github 😪

But, Your Project Is Really Excellent ✌✌

**Comment by MaxArt2501** [comment]
Thanks mate, have a good one!
