### ISSUE TITLE
How to change popover animation?

### ISSUE THREAD

**Issue by jerakode** [MaxArt2501/share-this#6]
Hi. Will I be able to change popover animation? How to do that? I found default animation pretty awful.

**Comment by MaxArt2501** [comment]
In the [`style`](https://github.com/MaxArt2501/share-this/tree/master/style) folder you can find the sources for the default stylesheet provided by the library, in both SCSS and LESS format. You can then extend and/or replace those rules.

In particular, you can just redefine the `share-this-intro` animation to something to your liking.

**Comment by jerakode** [comment]
@MaxArt2501 thank you, I will try.
