### ISSUE TITLE
controlling when to pop and when not ( based on selected text char length ) 

### ISSUE THREAD

**Issue by halukkaramete** [MaxArt2501/share-this#65]
Is there a way to determine when to pop and not to pop based on the selected text char length? 
Sometimes, you get a double click on a word, and this pop-up immediately fires, and clearly popping this for one word is false fire. 
Any solutions to remedy? 

Thank you

**Comment by MaxArt2501** [comment]
Yes, there is. The `active` property could be a function that returns whether the sharer should be used for a given selection or not.
If no sharer is made available for a given selection, the popover doesn't appear.

For an example of this, the demo page has a sharer that appears only if the selected text is uniquely found in the whole article. Check near the end:
https://maxart2501.github.io/share-this/dist/sharers/notes.js

**Comment by halukkaramete** [comment]
THank you for your reply. What I have ( unmodified ) is only this part. 

ShareThis({
	sharers: [ ShareThisViaTwitter,  ShareThisViaFacebook, ShareThisViaWhatsApp ],
	selector: "article"
}).init();

What can i do in here so my custom function can be called which can process the selectedText and then do preventDefault if the selectedText length is say less than 10 char?
