### ISSUE TITLE
Uncaught TypeError: Cannot set property 'ShareThis' of undefined

### ISSUE THREAD

**Issue by dlewand691** [MaxArt2501/share-this#7]
First off, thanks for creating and sharing this tool!

I'm a Mac user running Codekit and have copied your code from the demo page. I'm getting this error when the page loads:

`Uncaught TypeError: Cannot set property 'ShareThis' of undefined`

Any thoughts? Thnx!

**Comment by MaxArt2501** [comment]
I'm not familiar with Codekit so this is just my guess.

The only place that the property `ShareThis` gets set is when declaring it as a global variable. I didn't even write that part as it's being generated by Rollup as a UMD wrapper during the build process. Specifically, this is the snippet of the (possible) culprit, pretty printed:

```js
!function(e, t) {
    ...
    e.ShareThis = t()
}(this, function() { ...
```

The error you reported implies that `this` isn't defined when the code gets executed. Normally, it assumes the value of `window` or `global`, or whatever the "global" object is. It looks like it doesn't happen when the code is inside Codekit.

So possibly it's Codekit that's breaking UMD wrappers?

**Comment by dlewand691** [comment]
That's certainly possible that Codekit could be breaking it. The master .js file is linted with JSLint and transpiled with Babel for ES2015-2017. I'll tinker some more with the settings, etc and share what I find. Thanks!

**Comment by MaxArt2501** [comment]
No problem, let them know about it. I'll leave this open on the meanwhile.

**Comment by dlewand691** [comment]
So got it fixed. In Codekit you can define which Babel presets to use when compiling. I had ES2015, ES2016 and ES2015 enabled. Turning of ES2015 fixed it and then needed to add a higher z-index to the `.share-this-popover` class.

**Comment by MaxArt2501** [comment]
Great. So we can consider this issue closed, can we?
